# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        include_format: false
    body_converter:
        enabled: true
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json', prefer_extension: true}
            - { path: '^/', priorities: ['html'], fallback_format: 'html' }
    view:
        view_response_listener: true
    param_fetcher_listener: 'force'